# Generated by Django 5.2.6 on 2025-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='movies',
            field=models.ManyToManyField(related_name='orders', to='movies.movie'),
        ),
    ]
